name: Deploy

on:
  push:
    branches:
      - release

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # TODO: find a way to restore artifacts from build
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn workspace server build
      - name: Prepare artifacts
        run: |
          cd server/build
          yarn install --production
          tar -cvf ../../dist.tar ./*
          cd ../..
      - name: Deploy
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # ssh setups copied from: https://github.com/maddox/actions/blob/master/ssh/entrypoint.sh
        run: |
          SSH_PATH="$HOME/.ssh"
          mkdir -p "$SSH_PATH"
          touch "$SSH_PATH/known_hosts"
          echo "$SSH_PRIVATE_KEY" > "$SSH_PATH/deploy_key"
          chmod 700 "$SSH_PATH"
          chmod 600 "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/deploy_key"
          eval $(ssh-agent)
          ssh-add "$SSH_PATH/deploy_key"
          ssh-keyscan -t rsa $SSH_HOST >> "$SSH_PATH/known_hosts"

          scp -i $SSH_PATH/deploy_key ./dist.tar ci@sh.samuraime.com:/www/one-off/dist.tar
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd /www/one-off && tar -xf dist.tar -C ./ && pm2 restart ./process.json"
